# Generated by Django 5.2 on 2025-04-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0018_alter_configuraciones_qr_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banners',
        ),
    ]
