# Generated by Django 5.2 on 2025-04-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0019_delete_banners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulos',
        ),
    ]
