# Generated by Django 5.2 on 2025-04-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0020_delete_articulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='tags',
            field=models.TextField(blank=True, help_text='Palabras Clave. Separar por comas', null=True),
        ),
    ]
