# Generated by Django 5.2 on 2025-04-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0021_database_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='configuraciones',
            options={'verbose_name': 'Configuracion', 'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AlterModelOptions(
            name='database',
            options={'verbose_name': 'Base de Datos', 'verbose_name_plural': 'Bases de Datos'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeria'},
        ),
        migrations.AlterModelOptions(
            name='mapa',
            options={'verbose_name': 'Mapa', 'verbose_name_plural': 'Mapas'},
        ),
        migrations.AlterModelOptions(
            name='preguntas',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AddField(
            model_name='mapa',
            name='points',
            field=models.TextField(default='A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapa',
            name='tags',
            field=models.TextField(blank=True, help_text='Palabras Clave. Separar por comas', null=True),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cross_asistent.mapa', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='hide_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='uuid',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
