# Generated by Django 5.2 on 2025-05-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0022_alter_categorias_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galerias'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.RenameField(
            model_name='mapa',
            old_name='door_cords',
            new_name='coords',
        ),
    ]
