# Generated by Django 5.2 on 2025-05-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0023_alter_galeria_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapa',
            name='points',
        ),
        migrations.AlterField(
            model_name='mapa',
            name='coords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
