# Generated by Django 5.2 on 2025-05-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0024_remove_mapa_points_alter_mapa_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapa',
            name='p1_polygons',
        ),
        migrations.RemoveField(
            model_name='mapa',
            name='p2_polygons',
        ),
        migrations.RemoveField(
            model_name='mapa',
            name='p3_polygons',
        ),
        migrations.RemoveField(
            model_name='mapa',
            name='p4_polygons',
        ),
        migrations.AddField(
            model_name='mapa',
            name='door',
            field=models.CharField(blank=True, help_text='Coordenadas de la puerta separadas por comas', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='coords',
            field=models.TextField(blank=True, help_text='Coordenadas JSON del mapa', null=True),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='is_marker',
            field=models.BooleanField(default=False, help_text='Para los marcadores de imagen'),
        ),
    ]
