# Generated by Django 5.2 on 2025-05-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0025_remove_mapa_p1_polygons_remove_mapa_p2_polygons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapa',
            options={'verbose_name': 'Mapa', 'verbose_name_plural': 'Mapa'},
        ),
        migrations.AddField(
            model_name='mapa',
            name='otheraction',
            field=models.TextField(blank=True, help_text='Acciones adicionales', null=True),
        ),
    ]
