# Generated by Django 5.2 on 2025-06-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0026_alter_mapa_options_mapa_otheraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='status',
            field=models.CharField(default='Activo', max_length=20),
        ),
    ]
