# Generated by Django 5.2 on 2025-06-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0027_mapa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='access_to',
            field=models.TextField(blank=True, help_text='Acceso a este mapa', null=True),
        ),
    ]
