# Generated by Django 5.2 on 2025-06-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0028_mapa_access_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapa',
            name='access_to',
            field=models.TextField(blank=True, help_text='Acceso desde ciertas ubicaciones, ej. "Caseta 1, Caseta 2"', null=True),
        ),
    ]
