# Generated by Django 5.2 on 2025-08-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0029_alter_mapa_access_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='url',
            field=models.CharField(blank=True, help_text='URL del lugar', max_length=200, null=True),
        ),
    ]
